feelawesome/app/config/urls.py
from django.contrib import admin
from django.urls import path, include
from core.homepage.views import IndexView

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    # path('login/', include('core.login.urls')),
    path('admin/', admin.site.urls),
    path('dps/', include('core.dps.urls')),
    # path('user/', include('core.user.urls')),
]

feelawesome/app/core/dps/urls.py
from django.urls import path, include
# from core.dps.views.result.views import ResultView
# from core.dps.views.quiz.views import QuizView
from core.dps.views.quiz.views import quizview
from core.dps.views.result.views import resultview

app_name = 'dps'

urlpatterns = [
    # quiz
    path('quiz/', quizview, name='quiz'),
    # result
    path('result/', resultview, name='result'),
]

feelawesome/app/core/dps/models.py
from datetime import datetime
from secrets import choice

from django.db import models
from django.forms import model_to_dict

from core.dps.choices import gender_choices


# Create your models here.
class Patient(models.Model):
    gender = models.CharField(max_length=10, choices=gender_choices, default='male', verbose_name='Sexo',
                              db_column='pat_gender')
    graduate = models.CharField(max_length=100, verbose_name='Ciclo Academico', db_column='pat_graduate')
    faculty = models.CharField(max_length=100, verbose_name='Facultad')
    civil_status = models.CharField(max_length=100, verbose_name='Estado Civil')
    tfamily = models.CharField(max_length=100, verbose_name='Tipo de Familia')
    age = models.IntegerField(default=18, verbose_name='Edad')
    date_creation = models.DateField(default=datetime.now, verbose_name='Fecha de Creacion',
                                     db_column='pat_date_joined')

    def __str__(self):
        return '{} {} {} {}'.format(self.gender, self.graduate, self.faculty, self.age)

    def toJSON(self):
        item = model_to_dict(self)
        item['gender'] = {'id': self.gender, 'name': self.get_gender_display()}
        return item

    class Meta:
        verbose_name = 'Patient'
        verbose_name_plural = 'Patients'
        db_table = 'patients'
        ordering = ['id']


class BDI(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE, verbose_name='Paciente', db_column='pat_id')
    q1 = models.IntegerField()
    q2 = models.IntegerField()
    q3 = models.IntegerField()
    q4 = models.IntegerField()
    q5 = models.IntegerField()
    q6 = models.IntegerField()
    q7 = models.IntegerField()
    q8 = models.IntegerField()
    q9 = models.IntegerField()
    q10 = models.IntegerField()
    q11 = models.IntegerField()
    q12 = models.IntegerField()
    q13 = models.IntegerField()
    q14 = models.IntegerField()
    q15 = models.IntegerField()
    q16 = models.IntegerField()
    q17 = models.IntegerField()
    q18 = models.IntegerField()
    q19 = models.IntegerField()
    q20 = models.IntegerField()
    q21 = models.IntegerField()
    score = models.IntegerField()
    class_dep = models.IntegerField()

    def toJSON(self):
        item = model_to_dict(self)
        return item

    class Meta:
        verbose_name = 'BDI'
        verbose_name_plural = 'BDIs'
        db_table = 'bdis'
        ordering = ['id']


class Sack(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE, verbose_name='Paciente', db_column='pat_id')
    s1 = models.TextField()
    s2 = models.TextField()
    s3 = models.TextField()
    s4 = models.TextField()
    s5 = models.TextField()
    s6 = models.TextField()
    s7 = models.TextField()
    s8 = models.TextField()
    s9 = models.TextField()
    s10 = models.TextField()
    s11 = models.TextField()
    s12 = models.TextField()
    s13 = models.TextField()
    s14 = models.TextField()
    s15 = models.TextField()
    s16 = models.TextField()
    s17 = models.TextField()
    s18 = models.TextField()
    s19 = models.TextField()
    s20 = models.TextField()
    s21 = models.TextField()
    s22 = models.TextField()
    s23 = models.TextField()
    s24 = models.TextField()

    class Meta:
        verbose_name = 'Sack'
        verbose_name_plural = 'Sacks'
        db_table = 'sacks'
        ordering = ['id']

feelawesome/app/core/homepage/models.py
from django.db import models

# Create your models here.

feelawesome/app/core/dps/views/quiz/views.py
from django.http import JsonResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView


def quizview(request):
    return render(request, "quiz/instrument.html")

feelawesome/app/core/dps/views/result/views.py
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render
from sklearn.metrics import accuracy_score
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView
from core.dps.dpsmodels import PredictionDepressionModel

"""
class ResultView(TemplateView):
    template_name = 'result/predict.html'

    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            sx = request.POST['data']
            data['data'] = sx
            print(sx)
        except Exception as e:
            data['error'] = str(e)
        # context = self.get_context_data(**kwargs)
        return render(request, 'result/predict.html', data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        print(context)
        context['title'] = "Predicting Depression"
        return context
"""


def resultview(request):
    data = request.POST

    bdi1 = int(request.POST['bdi1'])
    bdi2 = int(request.POST['bdi2'])
    bdi3 = int(request.POST['bdi3'])
    bdi4 = int(request.POST['bdi4'])
    bdi5 = int(request.POST['bdi5'])
    bdi6 = int(request.POST['bdi6'])
    bdi7 = int(request.POST['bdi7'])
    bdi8 = int(request.POST['bdi8'])
    bdi9 = int(request.POST['bdi9'])
    bdi10 = int(request.POST['bdi10'])
    bdi11 = int(request.POST['bdi11'])
    bdi12 = int(request.POST['bdi12'])
    bdi13 = int(request.POST['bdi13'])
    bdi14 = int(request.POST['bdi14'])
    bdi15 = int(request.POST['bdi15'])
    bdi16 = int(request.POST['bdi16'])
    bdi17 = int(request.POST['bdi17'])
    bdi18 = int(request.POST['bdi18'])
    bdi19 = int(request.POST['bdi19'])
    bdi20 = int(request.POST['bdi20'])
    bdi21 = int(request.POST['bdi21'])

    values = [bdi1, bdi2, bdi3, bdi4, bdi5, bdi6, bdi7, bdi8, bdi9, bdi10, bdi11, bdi12, bdi13, bdi14, bdi15, bdi16,
              bdi17, bdi18, bdi19, bdi20, bdi21,
              bdi1 + bdi2 + bdi3 + bdi4 + bdi5 + bdi6 + bdi7 + bdi8 + bdi9 + bdi10 + bdi11 + bdi12 + bdi13 + bdi14 + bdi15 + bdi16 +
              bdi17 + bdi18 + bdi19 + bdi20 + bdi21]
    predictionbdimodel = PredictionDepressionModel()
    classifier = predictionbdimodel.decisionTree_classifier()
    prediction = classifier.predict([values])

    if prediction[0] == 1:
        result = 'Depresion Minima'
    if prediction[0] == 2:
        result = 'Depresion Leve'
    if prediction[0] == 3:
        result = 'Depresion Moderada'
    if prediction[0] == 4:
        result = 'Depresion Grave'

    # print(predictionbdimodel.accuracy(predictionbdimodel.svm_classifier()))
    # message = "Sexo {}".format(request.POST['sx'])
    return render(request, 'result/predict.html', {'message': result})

feelawesome/app/core/homepage/views.py
from django.shortcuts import render
from django.views.generic import TemplateView


# Create your views here.
class IndexView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "5MinTest"
        return context

feelawesome/app/core/dps/templates/result/predict.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
    {% include 'components/navbar.html' %}
    <section class="py-12">
            <h1 class="text-gray-600 text-center text-3xl mb-6">5MinTest Depression</h1>
            <p class="text-gray-600 text-center text-sm mb-6">El resultado de su nivel de depresion es: {{ message }}</p>
            <h4 class="text-gray-600 text-center text-xl mb-6"</h4>
            <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-x-6 gap-y-8">
                <article>
                    <p>Sexo</p>

                </article>

            </div>
    </section>

    {% include 'components/footer.html' %}
{% endblock %}

feelawesome/app/core/homepage/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
    {% include 'components/navbar.html'%}
    <section id="banner" class="bg-cover bg-center">
         <div class="max-w-7xl mx-auto px-4 py-36 sm:px-6 lg:px-8 text-black">
             <div class="w-full md:w-3/4 lg:w-1/2">
                 <h1 class="text-black font-bold text-4xl">Herramienta de calidad para la deteccion de la depresion</h1>
                 <p class="text-black text-lg mt-2 mb-4">Garantizamos una herramienta para la prediccion de la depresion.</p>
                 <!-- This is an example component -->
                 <div class="pt-2 relative mx-auto text-gray-600">

                     <div class="w-full bg-blue-500 hover:bg-blue-700 h-10 px-5 py-2 pr-16 rounded-lg text-center">
                         <a href="{% url 'dps:quiz' %}" class="no-underline text-white font-bold">Realizar prueba</a>
                     </div>
                 </div>
             </div>
         </div>
    </section>
    <section class="py-12">
        <h1 class="text-gray-600 text-center text-3xl mb-6">¿Por qué usar 5MinTtest?</h1>
        <p class="text-gray-600 text-center text-lg mb-6">Porque ponemos a su disposicion una excelente herramienta de
        prediccion de la depresion, con el fin de detectar el nivel de depresion de los que usan nuestro sistema.
        <br>Ademas manejamos diferentes tecnicas modernas de machine learning que ayudaran a reducir en corto tiempo</p>

        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 grid grid-cols-2 sm:grid-cols-1 lg:grid-cols-2 gap-x-6 gap-y-8">
            <article>
                <figure>
                    <img class="rounded-xl h-96 w-full object-cover" src="{% static 'img/sacks.jpg' %}" alt="">
                </figure>
                <header class="mt-2">
                    <h1 class="text-center text-xl text-gray-700">Test de Frases Incompletas</h1>
                </header>

                <p class="text-sm text-gray-500">
                    Fue   creado   con   el   fin   de   obtener   material   clínico   en   4   áreasrepresentativas
                    de la adaptación del sujeto  (familia, sexo, relacionesinterpersonales   y   autoconcepto),
                    considerando   que   los   reactivosincluidos en cada área ofrecerían suficientes oportunidades
                    para que elexaminado expresara sus propios deseos, temores, actitudes, etc., ensus respuestas
                    de tal manera que el examinador pudiera deducir cualeseran las tendencias dominantes de su personalidad.</p>
            </article>

             <article>
                <figure>
                    <img class="rounded-xl h-96 w-full object-cover" src="{% static 'img/bdi-ii.jpg' %}"  alt="">
                </figure>
                <header class="mt-2">
                    <h1 class="text-center text-xl text-gray-700">Inventario de Depresion de Beck (BDI-II)</h1>
                </header>

                <p class="text-sm text-gray-500">El Inventario de Depresion de Beck fue creado para
                Medir la severidad de depresión en adultos y adolescentes, a través de la evaluación de los
                    síntomas correspondientes a los criterios diagnósticos  de  los  trastornos  depresivos  en  el
                    Manual  Diagnóstico  y Estadísticos de trastornos Mentales </p>
            </article>

        </div>
    </section>


    {% include 'components/footer.html' %}
{% endblock %}

feelawesome/app/templates/base.html
{% load static %}
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    {% tailwind_css %}
    <!--Font Awesome-->
    <script defer src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" integrity="sha384-rOA1PnstxnOBLzCLMcre8ybwbTmemjzdNlILg8O7z1lUkLXozs4DHonlDtnE7fpc" crossorigin="anonymous"></script>
    <!--Boostrap-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!--Boostrap-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <!-- Development version -->
    <script src="https://unpkg.com/@popperjs/core@2/dist/umd/popper.js"></script>
    <!--Alpine JS-->
    <script src="//unpkg.com/alpinejs" defer></script>
    <!--Boxicons-->
    <script src="https://unpkg.com/boxicons@2.1.2/dist/boxicons.js"></script>
    <!-- Sweetalert2 -->
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <!--Jquery-Confirm-->
    <link rel="stylesheet" href="{% static 'lib/jquery-confirm-v3.3.4/jquery-confirm.min.css' %}">
    <script src="{% static 'lib/jquery-confirm-v3.3.4/jquery-confirm.min.js' %}"></script>    <!-- Functions -->
    <!-- My css -->
    <link rel="stylesheet" href="{% static 'css/mystyle.css' %}">
    <!-- Functions -->
    <script src="{% static 'js/functions.js' %}"></script>
    <!-- Block head -->
    {% block head %}

    {% endblock %}
</head>
<body>
    {% block body %}

    {% endblock %}
</body>
</html>

feelawesome/app/templates/components/banner.html
{% load static %}
 <section id="banner" class="bg-cover bg-center">
     <div class="max-w-7xl mx-auto px-4 py-36 sm:px-6 lg:px-8 text-black">
         <div class="w-full md:w-3/4 lg:w-1/2">
             <h1 class="text-black font-bold text-4xl">Educación inclusiva, equitativa y de calidad</h1>
             <p class="text-black text-lg mt-2 mb-4">Garantizamos una educación inclusiva, equitativa y de calidad y promover oportunidades de aprendizaje durante toda la vida para todos</p>
             <!-- This is an example component -->

             <div class="pt-2 relative mx-auto">
                 <button type="submit" class="w-full bg-blue-500 hover:bg-blue-700 h-10 px-5 pr-16 rounded-lg text-white font-bold">
                     Realizar Prueba
                 </button>
             </div>

            </div>
     </div>
 </section>

feelawesome/app/templates/components/footer.html
{% load static %}

<footer class="p-4 bg-white rounded-lg shadow md:flex md:items-center md:justify-between md:p-6 dark:bg-gray-800">
    <span class="text-sm text-gray-500 sm:text-center dark:text-gray-400">© 2022 <a href="{% url 'index' %}" class="hover:underline">5MinTest™</a>. All Rights Reserved.
    </span>
    <ul class="flex flex-wrap items-center mt-3 text-sm text-gray-500 dark:text-gray-400 sm:mt-0">
        <li>
            <a href="{% url 'index' %}" class="mr-4 no-underline hover:underline md:mr-6 ">Home</a>
        </li>
        <li>
            <a href="{% url 'dps:quiz' %}" class="mr-4 no-underline hover:underline md:mr-6">Quiz</a>
        </li>
        <li>
            <a href="#" class="mr-4 no-underline hover:underline md:mr-6">About</a>
        </li>
    </ul>
</footer>

feelawesome/app/templates/components/navbar.html
{% load static %}
<div x-data="{ open: false }" class="bg-white border-b border-gray-100 shadow">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex justify-between items-center border-b-2 border-gray-100 py-6 md:justify-start md:space-x-10">
            <div class="flex justify-start lg:w-0 lg:flex-1">
                <div class="flex-shrink-0 flex items-center">
                    <a href="{% url 'index' %}">
                        <img class="block h-9 w-auto" src="https://img.icons8.com/color/48/000000/neural_connections.png"/>
                    </a>
                </div>
                <div class="flex-shrink-0 flex items-center ml-2 text-xl font-semibold">
                    <a class="no-underline text-black" href="{% url 'index' %}">5MinTest</a>
                </div>
            </div>
            <!-- Hamburger -->
            <div class="-mr-2 -my-2 md:hidden">
                <button @click="open=true" type="button" class="bg-white rounded-md p-2 inline-flex items-center justify-center text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-indigo-500" aria-expanded="false">
                    <span class="sr-only">Open menu</span>
                    <!-- Heroicon name: outline/menu -->
                    <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
                    </svg>
                </button>
            </div>
            <nav class="hidden md:flex space-x-10">
                <a href="{% url 'index' %}" class="text-base font-medium text-gray-500 hover:text-gray-900 no-underline hover:underline"> Home </a>
                <a href="{% url 'dps:quiz' %}" class="text-base font-medium text-gray-500 hover:text-gray-900 no-underline hover:underline"> Quiz </a>
                <!--<a href="#" class="text-base font-medium text-gray-500 hover:text-gray-900 no-underline hover:underline"> About </a>-->
            </nav>
            <div class="hidden md:flex items-center justify-end md:flex-1 lg:w-0">
            </div>
        </div>
    </div>
    <div x-show="open" @click.away="open=false" x-transition:enter="ease-out duration-300" x-transition:enter-start="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95" x-transition:enter-end="opacity-100 translate-y-0 sm:scale-100" x-transition:leave="ease-in duration-200" x-transition:leave-start="opacity-100 translate-y-0 sm:scale-100" x-transition:leave-end="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95" class="absolute top-0 inset-x-0 p-2 transition transform origin-top-right md:hidden">
        <div class="rounded-lg shadow-lg ring-1 ring-black ring-opacity-5 bg-white divide-y-2 divide-gray-50">
            <div class="pt-5 pb-6 px-5">
                <div class="flex items-center justify-between">
                    <div class="flex-shrink-0 flex items-center">
                        <a href="{% url 'index' %}">
                            <img class="block h-9 w-auto" src="https://img.icons8.com/color/48/000000/neural_connections.png"/>
                        </a>
                        <span class="ml-2">5MinTest</span>
                    </div>
                    <div class="-mr-2">
                        <button @click="open=false" type="button" class="bg-white rounded-md p-2 inline-flex items-center justify-center text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-indigo-500">
                            <span class="sr-only">Close menu</span>
                            <!-- Heroicon name: outline/x -->
                            <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                                </svg>
                        </button>
                    </div>
                </div>
                <div class="py-6 px-5 space-y-6">
                    <div class="grid grid-cols-2 gap-y-4 gap-x-8">
                        <a href="{% url 'index' %}" class="text-base font-medium text-gray-900 hover:text-gray-700 no-underline hover:underline"> Home </a>
                        <a href="{% url 'dps:quiz' %}" class="text-base font-medium text-gray-900 hover:text-gray-700 no-underline hover:underline"> Quiz </a>
                        <!--<a href="#" class="text-base font-medium text-gray-900 hover:text-gray-900 no-underline hover:underline"> About </a>-->
                    </div>
                    <div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

feelawesome/app/templates/home.html
{% extends 'base.html' %}

{% block body %}
    {% include 'components/navbar.html' %}

    {% include 'components/footer.html' %}
{% endblock %}

feelawesome/app/theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Django Tailwind</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body class="bg-gray-50 font-serif leading-normal tracking-normal">
		<div class="container mx-auto">
			<section class="flex items-center justify-center h-screen">
				<h1 class="text-5xl">Django + Tailwind = ❤️</h1>
			</section>
		</div>
	</body>
</html>